### ISSUE TITLE
Ambiguous operations String getFQN(EClassifier this,String separator) and String getFQN(EOperation this,String separator) for param types [Void, String]

### ISSUE THREAD

**Issue by mario-van-zadel** [catedrasaes-umu/emf4cpp#17]
Hi,

when trying to generate C++ files for the [Xbase.ecore](https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/model/Xbase.ecore) meta model, I'm getting the following exception:

```
Exception in thread "main" EvaluationException : Ambiguous operations String getFQN(EClassifier this,String separator) and String getFQN(EOperation this,String separator) for param types [Void, String]
	template::EClassHPP.xpt[1681,15] on line 52 'pkg.getFQN("/")'
	template::Main.xpt[1551,71] on line 43 'EXPAND template::EClassHPP::hpp FOREACH EClassifiers.typeSelect(EClass)'
	template::Main.xpt[1093,23] on line 30 'EXPAND package FOR this'

	at org.eclipse.internal.xtend.expression.ast.Expression.evaluate(Expression.java:59)
	at org.eclipse.internal.xpand2.ast.ExpressionStatement.evaluateInternal(ExpressionStatement.java:45)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.ForEachStatement.evaluateInternal(ForEachStatement.java:121)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.FileStatement.evaluateInternal(FileStatement.java:86)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.AbstractDefinition.evaluate(AbstractDefinition.java:178)
	at org.eclipse.internal.xpand2.ast.ExpandStatement.invokeDefinition(ExpandStatement.java:246)
	at org.eclipse.internal.xpand2.ast.ExpandStatement.evaluateInternal(ExpandStatement.java:190)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.AbstractDefinition.evaluate(AbstractDefinition.java:178)
	at org.eclipse.internal.xpand2.ast.ExpandStatement.invokeDefinition(ExpandStatement.java:246)
	at org.eclipse.internal.xpand2.ast.ExpandStatement.evaluateInternal(ExpandStatement.java:226)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.IfStatement.evaluateInternal(IfStatement.java:101)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.IfStatement.evaluateInternal(IfStatement.java:96)
	at org.eclipse.internal.xpand2.ast.Statement.evaluate(Statement.java:41)
	at org.eclipse.internal.xpand2.ast.AbstractDefinition.evaluate(AbstractDefinition.java:178)
	at org.eclipse.xpand2.XpandFacade.evaluate2(XpandFacade.java:62)
	at org.eclipse.xpand2.XpandFacade.evaluate(XpandFacade.java:43)
	at org.csu.emf4cpp.generator.Generator.generate(Generator.java:102)
	at org.csu.emf4cpp.generator.Generator.main(Generator.java:199)
Caused by: java.lang.RuntimeException: Ambiguous operations String getFQN(EClassifier this,String separator) and String getFQN(EOperation this,String separator) for param types [Void, String]
	at org.eclipse.internal.xtend.type.baseimpl.PolymorphicResolver.getFeature(PolymorphicResolver.java:112)
	at org.eclipse.internal.xtend.type.baseimpl.PolymorphicResolver.getExtension(PolymorphicResolver.java:56)
	at org.eclipse.xtend.expression.ExecutionContextImpl$ExtensionsForNameAndTypeCache.createNew(ExecutionContextImpl.java:97)
	at org.eclipse.xtend.expression.ExecutionContextImpl$ExtensionsForNameAndTypeCache.createNew(ExecutionContextImpl.java:1)
	at org.eclipse.internal.xtend.util.Cache.get(Cache.java:26)
	at org.eclipse.xtend.expression.ExecutionContextImpl.getExtensionForTypes(ExecutionContextImpl.java:371)
	at org.eclipse.xtend.expression.ExecutionContextImpl.getExtension(ExecutionContextImpl.java:382)
	at org.eclipse.internal.xtend.expression.ast.OperationCall.evaluateInternal(OperationCall.java:117)
	at org.eclipse.internal.xtend.expression.ast.Expression.evaluate(Expression.java:51)
	... 23 more
```

I use the following command to generate the C++ classes:

```
java -jar "org.csu.emf4cpp.generator_2.0.0.jar" -o ../../src/ecore Xbase.ecore
```

Has anyone an idea why this exception occurs? The causing call should be this one: https://github.com/catedrasaes-umu/emf4cpp/blob/master/org.csu.emf4cpp.generator/src/template/EClassHPP.xpt#L52 

I'm not sure if there's a problem with the Xbase meta-model or if I configured the emf4cpp-generator the wrong way.

Thanks in advance for your help!

Regards
Mario

**Comment by srhenning** [comment]
Hi Mario,

the problem is caused by using EClasses, that are defined in another ecore:

platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore

Classes from this ecore are used as base classes as well as eType for structural features. This is supported by emf4cpp in principle, but not via the platform mechanism. Instead a relative path to the ecore must by given in the reference. To use the library you have to generate code for the referenced ecore.

I hope that helps you. I am at your disposal for further questions.
Yours sincerely
Sören

**Comment by mario-van-zadel** [comment]
Thank you very much, @srhenning!

Referencing the other ecores by using relative paths worked fine!

For example, I had to change
```
<eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter" containment="true"/>
```
to
```
<eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="ecore:EClass JavaVMTypes.ecore#//JvmFormalParameter" containment="true"/>
```

in case of the `JavaVMTypes.ecore` stored in the same (current) directory.

Regards
Mario
